book/urls.py
from django.contrib import admin
from django.urls import include, path

from django.urls import path, re_path

from . import views


app_name ="book"


urlpatterns = [
    re_path(r'^(?P<slug>[-\w]+)/$', views.BookDetailView.as_view(), name='book-detail'),
    re_path(r'^category/(?P<category_slug>[-\w]+)/$', views.CategoryDetailView.as_view(), name='list_category'),
    re_path(r'^$', views.BookListView.as_view(), name="book_list")

]

bookstore/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from book import views


urlpatterns = [
      path('orders/', include('orders.urls')),
      path('books/', include('book.urls')),
      re_path(r'^delivery/$', TemplateView.as_view(template_name='delivery.html'), name="delivery"),
      re_path(r'^payments/$', TemplateView.as_view(template_name='payments.html'), name="payments"),
      re_path(r'^grafik-raboty/$', TemplateView.as_view(template_name='grafic.html'), name="grafik-raboty"),
      re_path(r'^returns/$', TemplateView.as_view(template_name='returns.html'), name="returns"),
      re_path(r'^about/$', TemplateView.as_view(template_name='about.html'), name="about"),
      path('admin/', admin.site.urls),
      path('', include('book.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
              # + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \

orders/urls.py
from django.contrib import admin
from django.urls import include, path

from django.urls import path, re_path

from . import views

app_name = 'orders'

urlpatterns = [
    re_path('^basket_adding/$', views.basket_adding, name='basket_adding'),
    re_path('^cart/$', views.cart, name='cart'),
    re_path('^checkout/$', views.checkout, name='checkout'),
    re_path('^remove_from_cart/$', views.remove_from_cart_view, name='remove_from_cart'),
    re_path('^count_cart/$', views.basket_count, name='basket_count'),
    re_path('^change_item_qty/$', views.change_item_qty, name='change_item_qty'),
    re_path('^order/$', views.order_create_view, name='create_order'),
    re_path('^make_order/$', views.make_order, name='make_order'),
]

book/models.py
from django.db import models
from django.db.models.signals import pre_save
from transliterate import translit
from django.urls import reverse
from django.utils.text import slugify
# Create your models here.


class BookCategory(models.Model):
    name = models.CharField(max_length=64, blank=True, null=True, default=None)
    slug = models.SlugField(max_length=128, blank=True, null=True, default=None, unique=True)
    is_active = models.BooleanField(default=True)

    def get_absolute_url(self):
        return reverse('book:list_category', args=[str(self.slug)])

    def __str__(self):
        return ' {}'.format(self.name)

    class Meta:
        verbose_name = 'Категория книги'
        verbose_name_plural = 'Категория книг'

def pre_save_category_slug(sender,instance,*args,**kwargs):
    if not instance.slug:
        slug = slugify(translit(str(instance.name), reversed=True))
        instance.slug = slug


pre_save.connect(pre_save_category_slug, sender=BookCategory)


class Book(models.Model):
    name = models.CharField(max_length=128,blank=True, null=True, default=None)
    slug = models.SlugField(max_length=128,blank=True, null=True, default=None)
    description = models.TextField(blank=True, null=True, default=None)
    discount = models.IntegerField(default=0)
    category = models.ForeignKey(BookCategory, blank=True, null=True, default=None,on_delete=models.CASCADE)
    short_description = models.TextField(blank=True, null=True, default=None)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=None)
    is_active = models.BooleanField(default=True)
    created = models.DateField(auto_now_add=True, auto_now=False)
    updated = models.DateField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return ' {}'.format(self.name)

    def get_absolute_url(self):
        return reverse('book:book-detail', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = 'Книга'
        verbose_name_plural = 'Книги'


def pre_save_book_slug(sender,instance,*args,**kwargs):
    if not instance.slug:
        slug = slugify(translit(str(instance.name), reversed=True))
        instance.slug = slug


pre_save.connect(pre_save_book_slug, sender=Book)

class BookImage(models.Model):
    book = models.ForeignKey(Book,blank=True, null=True, default=None,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='book_images/')
    is_active = models.BooleanField(default=True)
    is_main = models.BooleanField(default=False)
    created = models.DateField(auto_now_add=True, auto_now=False)
    updated = models.DateField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return ' {}'.format(self.id)

    def get_absolute_url(self):
        return reverse('book:book-detail', kwargs={'slug': self.book.slug})


    class Meta:
        verbose_name = 'Фотография книги'
        verbose_name_plural = 'Фотографии книг'
        ordering = ['-id']


class Visual(models.Model):
    book = models.ForeignKey(Book,blank=True, null=True, default=None,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='visual/')
    is_active = models.BooleanField(default=True)
    created = models.DateField(auto_now_add=True, auto_now=False)
    updated = models.DateField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return ' {}'.format(self.id)

    def get_absolute_url(self):
        return reverse('book:book-detail', kwargs={'slug': self.book.slug})


    class Meta:
        verbose_name = 'Картинка слайдера'
        verbose_name_plural = 'Картинки слайдера'

book/views.py
from django.views.generic import ListView, DetailView
from book.models import Book, BookImage,BookCategory,Visual
from django.shortcuts import get_object_or_404, get_list_or_404,render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.
class BookListView(ListView):
    model = BookImage
    template_name = 'home.html'


    def get_context_data(self, **kwargs):
        context = super(BookListView, self).get_context_data(**kwargs)
        images_books = BookImage.objects.filter(is_active=True, is_main=True,book__is_active=True)
        context['images_books'] = images_books
        context['product_images_hit'] = images_books.filter(book__category__name='Хиты продаж')
        context['product_images_new'] = images_books.filter(book__category__name='Новинки')
        context['product_images_last_add'] = images_books.filter(book__category__name='Последние поступления')
        context['product_images_sell_it'] = images_books.filter(book__category__name='Раcпродажа')
        context['product_images_recommended_books'] = images_books.filter(book__category__name='Рекомендуемые книги')
        context['images_for_slider']= Visual.objects.filter(is_active=True)
        session_key = self.request.session.session_key
        if not session_key:
            self.request.session.cycle_key()
        return context


class BookDetailView(DetailView):
    model = Book
    template_name = "book/book.html"
    context_object_name = "detail_book"

    def get_object(self):
        return get_object_or_404(Book, slug=self.kwargs['slug'])


class CategoryDetailView(ListView):
    model = BookImage
    template_name = "book/book_category.html"
    paginate_by = 8
    context_object_name = 'contacts'

    def get_context_data(self, **kwargs):
            context = super(CategoryDetailView, self).get_context_data(**kwargs)
            category = BookCategory.objects.get(slug=self.kwargs['category_slug'])
            context['category'] = category
            return context

    def get_queryset(self):
        return  BookImage.objects.filter(book__category__slug=self.kwargs['category_slug'],
                                         is_active=True, is_main=True, book__is_active=True)

templates/book/book.html
{% extends "base.html"%}
{% load static %}
{% block content%}

 <!-- Page Content -->
<div class="container">
    <div class="row">
            <div class="text-header">
            <h3 class="text-center">{{detail_book.name}}</h3>
            </div>

    <div class="col-md-6">
        <div class="container">
		<div class="albery-container img ">
			<div class="albery-wrapper img">
                  {% for image_item in detail_book.bookimage_set.all.reverse %}
				<div class="albery-item img  ">
					<img src="{{image_item.image.url}}" class="img-item" alt="">
				</div>
				{% endfor %}
			</div>
			<div class="move-right">
				<a href="#" id="rightArrow"></a>
			</div>
			<div class="move-left">
				<a href="#" id="leftArrow"></a>
			</div>
		</div>
		<div class="pagination-container">
			<div class="pagination-wrapper">
                {% for image_item in detail_book.bookimage_set.all.reverse %}
				<div class="pagination-item" data-item="{{ forloop.counter }}">
					<img src="{{image_item.image.url}}" alt="">
				</div>
                {% endfor%}

			</div>
		</div>
</div>


    </div>

    <div class="col-md-6">

        <div class="detail-price">
            <h5>Цена: {{detail_book.price}}</h5>
        </div>
        <div class="detail-description">
            <p> {{detail_book.description}}</p>
        </div>


       <form  class="form-inline form_buying_book justify-content-left" action="{% url 'orders:basket_adding'%}">{% csrf_token %}
                   <input type="number" value="1"   class="form-control number" style="width:50px" min="1" >

                   <div class="form-group ">
                     <button type="submit" class="btn btn-success btn-buy submit_btn  "

                          data-product_id = '{{ detail_book.id }}'
                          data-name = '{{detail_book.name}}'
                          data-price = '{{ detail_book.price }}'
                     >
                       Купить
                     </button>
                   </div>
    </form>

    </div>

  </div>
  <!-- /.row -->

</div>
<!-- /.container -->





{% endblock%}

templates/book/book_category.html
{% extends "base.html"%}
{% load static %}
{% block content%}


<h1 class="text-center"> {{category}}  </h1>
<div class="row">
  {% for img_book in contacts %}
            {% include "book/book_item.html"%}
  {% endfor %}

</div>

{% include "book/pagination.html" %}

{% endblock%}

templates/book/book_item.html
<div class="col-lg-3 col-md-4 mb-3">
    <div class="product-item">
          <div class="img-fluid mx-auto d-block">
            <a href="{{img_book.get_absolute_url}}" >
                     <img src="{{img_book.image.url}}" class="item-image">
            </a>
          </div>
          {% if img_book.book.discount%}
              <div class="discount-container">
                  <span>{{img_book.book.discount}}</span>
              </div>
          {% endif %}
          <div class="item-title">
            <h6>{{ img_book.book.name }}</h6>
          </div>
          <div class="item-desc">
             <p>{{ img_book.book.description}}</p>
          </div>
          <div class="item-price">
              <p>  Цена: {{img_book.book.price}} UAH</p>
          </div>
            <div class="add-btn text-center   ">
            <form  class="form-inline form_buying_book justify-content-center" action="{% url 'orders:basket_adding'%}">{% csrf_token %}
                   <input type="number" value="1"   class="form-control number" style="width:50px" min="1" >

                   <div class="form-group ">
                     <button type="submit" class="btn btn-success btn-buy submit_btn  "

                         data-product_id = '{{ img_book.book.id }}'
                         data-name = '{{img_book.book.name}}'
                         data-price = '{{ img_book.book.price }}'
                     >
                       Купить
                     </button>
                   </div>
             </form>
          </div>
    </div>
</div>

templates/book/pagination.html
{% block pagination %}
{% if is_paginated %}
    <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-left">
      {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
      {% else %}
      <li class="page-item disabled"><a class="page-link" href="#"><span>&laquo;</span></a></li>
      {% endif %}
      {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
      <li class="page-item active"><a class="page-link" href="#">{{ i }} <span class="sr-only">(current)</span></a></li>
      {% else %}
      <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
      {% else %}
      <li class="page-item disabled"><a class="page-link" href="#"><span>&raquo;</span></a></li>
      {% endif %}
    </ul>
    </nav>
{% endif %}
{% endblock %}