book/urls.py
from django.contrib import admin
from django.urls import include, path

from django.urls import path, re_path

from . import views


app_name ="book"


urlpatterns = [
    re_path(r'^(?P<slug>[-\w]+)/$', views.BookDetailView.as_view(), name='book-detail'),
    re_path(r'^category/(?P<category_slug>[-\w]+)/$', views.CategoryDetailView.as_view(), name='list_category'),
    re_path(r'^$', views.BookListView.as_view(), name="book_list")

]

bookstore/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from book import views


urlpatterns = [
      path('orders/', include('orders.urls')),
      path('books/', include('book.urls')),
      re_path(r'^delivery/$', TemplateView.as_view(template_name='delivery.html'), name="delivery"),
      re_path(r'^payments/$', TemplateView.as_view(template_name='payments.html'), name="payments"),
      re_path(r'^grafik-raboty/$', TemplateView.as_view(template_name='grafic.html'), name="grafik-raboty"),
      re_path(r'^returns/$', TemplateView.as_view(template_name='returns.html'), name="returns"),
      re_path(r'^about/$', TemplateView.as_view(template_name='about.html'), name="about"),
      path('admin/', admin.site.urls),
      path('', include('book.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
              # + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \

orders/urls.py
from django.contrib import admin
from django.urls import include, path

from django.urls import path, re_path

from . import views

app_name = 'orders'

urlpatterns = [
    re_path('^basket_adding/$', views.basket_adding, name='basket_adding'),
    re_path('^cart/$', views.cart, name='cart'),
    re_path('^checkout/$', views.checkout, name='checkout'),
    re_path('^remove_from_cart/$', views.remove_from_cart_view, name='remove_from_cart'),
    re_path('^count_cart/$', views.basket_count, name='basket_count'),
    re_path('^change_item_qty/$', views.change_item_qty, name='change_item_qty'),
    re_path('^order/$', views.order_create_view, name='create_order'),
    re_path('^make_order/$', views.make_order, name='make_order'),
]

templates/about.html
{% extends "base.html"%}
{% load static %}
{% block content%}
<h1>О Компании</h1>


								<div>
	 Bookstore -&nbsp;молодой, но активно развивающийся интернет-магазин книг. Наша амбициозная команда работает над проектом, стремясь создать максимально комфортные и выгодные условия для всех ценителей хорошей литературы. Мы можем предложить читателям более 30 тысяч наименований книг разных жанров. Bookstore&nbsp;– интернет-магазин книг, который облегчает поиск и приобретение качественной продукции.&nbsp;
</div>
<div>
 <span style="font-size: 14pt;"><b>У нас на сайте Вы сможете найти книги на все случаи жизни:</b></span><br>
</div>
<ul>
	<li>произведения мировой классики, которые не утратят своей актуальности;</li>
	<li>
	бестселлеры, которые уже завоевали признание читателей всего мира;</li>
	<li>
	актуальные новинки книжного мира;</li>
	<li>
	познавательная литература на любую тему;</li>
	<li>
	книги для личностного роста и развития бизнеса;</li>
	<li>
	красочные книги для детей;</li>
	<li>
	информационно-справочные издания;</li>
	<li>
	отличные подарочные книги.</li>
</ul>
 <br>
 &nbsp;Весь ассортимент книг, представленный на сайте, проходит тщательную проверку. Возможность появления некачественных экземпляров исключена.<br>
 <b>&nbsp;</b><span style="font-size: 14pt;"><b>Почему Вам стоит сотрудничать с нами?</b></span><br>
<ul>
	<li>все позиции, представленные на сайте, есть в наличии на складе;</li>
	<li>
	мы предлагаем актуальную литературу и новинки лучших авторов со всего мира;</li>
	<li>
	привлекательные скидки, интересные акции и бонусы для наших клиентов;</li>
	<li>
	заказ будет доставлен в любую точку Украины в короткие сроки;</li>
	<li>
	максимально удобные способы оплаты для клиентов;</li>
	<li>
	налаженная система обратной связи.</li>
</ul>
 <br>
 Мы ценим наших клиентов и всегда рады новым покупателям. Наша задача – сделать Ваш досуг полезным, незабываемым и приятным.<br>
<p>
</p>
<p>
</p>
<p>
</p>
{% endblock  %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Интернет магазин книг</title>
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon/favicon-16x16.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon/favicon-16x16.ico' %}">

    <!-- Bootstrap-->
    <!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.min.css">-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">

    <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400" rel="stylesheet">
    <link href="https://www.jqueryscript.net/css/jquerysctipttop.css" rel="stylesheet" type="text/css">
    <!-- Custom styles -->
    <link rel="stylesheet" href="{% static 'css/albery.css' %}">
    <link rel="stylesheet" href="{% static 'css/footer.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">


</head>
<body>
 {% include "navbar.html"%}

  <!-- Page Content -->
  <div class="container">
      <div class="wrapper-content">
        <div class="row">
             {% include "sidebar.html"%}
         <div class="col-lg-9">
                {% block content%}
                 {% endblock %}
         </div>
          <!-- /.col-lg-9 -->
        </div>
        <!-- /.row -->
          </div>
      {% include "footer.html"%}
  </div>

  <!-- /.container -->








            <!-- jQuery -->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"> </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"> </script>
    <script src="{% static 'js/scripts.js' %}"></script>
    <script src="{% static 'js/albery.js' %}"></script>
    <script>
		$(".albery-container").albery({
			speed: 500,
			imgWidth: 220,
		});
	</script>




</body>
</html>

templates/delivery.html
{% extends "base.html"%}
{% load static %}
{% block content%}

 <!-- Page Content -->


<h3 class="text-left">Доставка</h3>
<h5 class="text-center">Уважаемые клиенты!</h5>
<p> Доставка осуществляется в течении 1-3 дней после оформления заказа.Иногда, в случае отправки с удалённого склада, доставка может занять до 7 дней.</p>
<p>Мы понимаем, как важно для Вас, чтобы посылка пришла в срок, поэтому работаем с лидером на рынке доставок – Новой почтой.</p>
<p>Если стоимость Вашего заказа больше 600 гривен, мы оплатим доставку сами*</p>

<h5 class="text-center">Способы доставки</h5>
<h6 class="font-weight-bold"><i>Курьерская доставка по Киеву</i> </h6>
<p> Доставка осуществляется в течении 1-3 дней после оформления заказа.</p>
<p>Стоимость доставки – 55 гривен.</p>
<h6 class="font-weight-bold"> <i>Доставка на склад Новой Почты </i></h6>

<p><ins>Для жителей Киева:</ins></p>
<p>Если Вы сделали заказ сегодня:</p>
<p>- до 16.00 - посылка появиться в пункте выдачи на следующий день;</p>
<p>- после 16.00 - Вы сможете забрать свою посылку в отделении через день.</p>
<p><ins> Для жителей Украины:</ins></p>
<p>Этот способ доставки гарантирует Вам получение товара даже в самых отдаленных населенных пунктах Украины.</p>
<p>Сроки получения – от 1 до 3 дней. </p>
<p>Стоимость доставки на склад «Новой почты» - 45 гривен.</p>
<p>Стоимость доставки крупногабаритных товаров осуществляется по тарифам «Новой почты». Узнать более детальную информацию о графике работы и адресах отделений Вы можете на сайте компании «Новая Почта». Для получения товара Вам нужно будет обратиться в назначенное отделение после смс-сообщения о прибытии товара. При себе нужно иметь паспорт и знать номер декларации.</p>
<p class="font-weight-bold">*Бесплатная доставка действует на заказ с итоговой стоимостью от 600 грн. (с учетом примененных скидок), отправляемый одной посылкой. В случае, когда книги из одного заказа, оформленного на сумму свыше 600 грн., находятся на различных складах, сумма заказа делится на две части и обе посылки доставляются бесплатно вне зависимости от их стоимости.</p>

{% endblock%}

templates/footer.html
<!-- Footer -->
	<section id="footer">
		<div class="container">
			<div class="row text-center text-xs-center text-sm-left text-md-left">
				<div class="col-xs-12 col-sm-4 col-md-4">
					<h5><a href="{% url 'book:book_list'%}">Главная</a></h5>
					<ul class="list-unstyled quick-links">
						<li><a  href="{% url 'returns'%}"><i class="fa fa-angle-double-right"></i>Возврат и обмен</a></li>
					</ul>
				</div>
				<div class="col-xs-12 col-sm-4 col-md-4">
					<h5><a  href="{% url 'grafik-raboty'%}">График работы</a></h5>
					<ul class="list-unstyled quick-links">

						<li><a href="{% url 'payments'%}"><i class="fa fa-angle-double-right"></i>Оплата</a></li>

					</ul>
				</div>
				<div class="col-xs-12 col-sm-4 col-md-4">
					<h5><a href="{% url 'about'%}">О нас</a></h5>
					<ul class="list-unstyled quick-links">

					</ul>
				</div>
			</div>

			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center text-black">
					<p class="h6">&copy All right Reversed.</p>
				</div>
				</hr>
			</div>
		</div>
	</section>
	<!-- ./Footer -->

templates/grafic.html
{% extends "base.html"%}
{% load static %}
{% block content%}
<div>
<h1>График работы</h1>


								<b>Мы принимаем заказы на сайте:<br>
 </b>
<div>
 <b> </b>
</div>
<div>
</div>
<div>
</div>
<div>
 <br>
</div>
<div>
</div>
<div>
	 Ежедневно, круглосуточно<b> </b>и безостановочно<b> 24/7/365</b>
</div>
<div>
</div>
<div>
 <br>
</div>
<div>
 <b>Мы готовы связаться с вами по телефону: </b><br>
</div>
<div>
 <br>
</div>
<div>
 <br>
</div>
<div>
</div>
<div>
</div>
<div>
	 Понедельник - 09.00 - 19.00<br>
	 Вторник - 09.00 - 19.00<br>
	 Среда - 09.00 - 19.00<br>
	 Четверг - 09.00 - 19.00<br>
	 Пятница - 09.00 - 19.00 <br>
	 Суббота - 10.00 - 19.00
</div>
 Воскресенье - 10.00 - 19.00
<div>
 <b><br>
 </b>
</div>
<div>
 <b><br>
 </b>
</div>
<div>
 <b>Мы собираем и отправляем Вам любимые книги:</b>
</div>
<div>
 <br>
</div>
<div>
	 Понедельник - 09.00 - 19.00
</div>
 Вторник - 09.00 - 19.00
<div>
	 Среда - 09.00 - 19.00
</div>
 Четверг - 09.00 - 19.00
<div>
	 Пятница - 09.00 - 19.00 <br>
</div>
<div>
	 Ждём понедельника.<br>
</div>
 <br>							</div>
{%  endblock %}

templates/home.html
{% extends "base.html"%}
{% load static %}
{% block content%}

{% include "slider.html"%}

<h1 class="text-center"> Новинки  </h1>
<div class="row">
  {% for img_book in product_images_new|slice:":8"  %}
            {% include "book/book_item.html"%}
  {% endfor %}
</div>
<!-- /.row -->


<h1 class="text-center"> Хиты продаж  </h1>
<div class="row">
 {% for img_book in product_images_hit|slice:":8" %}
            {% include "book/book_item.html"%}
 {% endfor %}
</div>
<!-- /.row -->

  <h1 class="text-center"> Рекомендуемые книги  </h1>
<div class="row">
  {% for img_book in product_images_recommended_books|slice:":8" %}
            {% include "book/book_item.html"%}
  {% endfor %}
</div>
<!-- /.row -->

<h1 class="text-center"> Последние поступления  </h1>
<div class="row">
  {% for img_book in product_images_last_add|slice:":8" %}
            {% include "book/book_item.html"%}
  {% endfor %}
</div>
<!-- /.row -->

<h1 class="text-center"> Раcпродажа  </h1>
<div class="row">
  {% for img_book in product_images_sell_it|slice:":8" %}
            {% include "book/book_item.html"%}
  {% endfor %}
</div>
<!-- /.row -->
{% endblock %}

templates/navbar.html
{% load static %}
<!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark  nav-color fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'book:book_list'%}">
          <img src="{% static 'img/logo.png' %}" alt="">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">


        <ul class="navbar-nav mx-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'book:book_list'%}">Главная
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'payments'%}">Оплата</a>
          </li>
           <li class="nav-item">
            <a class="nav-link" href="{% url 'about'%}"> О нас</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'grafik-raboty'%}"> График работы</a>
          </li>

        </ul>
        <ul class="navbar-nav lx-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'orders:cart'%}">Корзина</a>
          </li>
            <li class="nav-item">
                <div class=" basket-container " >
                  <span id="basket_total_amount"></span>
                  <a class="basket-count not-active"  href="{% url 'orders:basket_count'%}">
                      <span id="basket_total_nmb" >
                      {% if products_total_nmb %}
                          ({{products_total_nmb}})
                      {% else %}
                          (0)
                      {% endif %}
                      </span>
                  </a>
                </div>
            </li>
        </ul>



      </div>
    </div>
  </nav>

templates/payments.html
{% extends "base.html"%}
{% load static %}
{% block content%}

 <!-- Page Content -->


<h3 class="text-left">Способы оплаты</h3>
<h5>Оплата на сайте LiqPay</h5>
<p>Очень удобный и быстрый способ оплатить заказ. Вы можете совершать платежи в любое удобное для Вас время.</p>
<h6>Варианты оплаты:</h6>
<div>
    <blockquote>
		<ul>
			<li>Оплата банковской картой - оплата без регистрации на сайте LiqPay. </li>
			<li>
			Приват24 - оплата на сайте системы Приват 24.&nbsp; </li>
			<li>
			В терминале - оплата наличными или картой в терминале Приват Банка.  </li>
			<li>
			Оплата&nbsp;через&nbsp;<a href="#">LiqPay</a> - авторизуйтесь на сайте LiqPay и оплатите товар&nbsp;через него. </li>
			<li>
			Счет на оплату, который высылается Вам на электронный адрес.</li>
			<li>
			<p>
				 MasterPass. Возможность быстро и безопасно&nbsp;осуществить платеж при помощи электронного кошелька.&nbsp; &nbsp;
			</p>
			</li>
		</ul>
	</blockquote>
</div>
<div>
    <h5>Рассрочка.</h5>
    <p>
	 Если Вам понравились сразу несколько книг, но&nbsp;Вы не планировали потратить такую сумму – оформите моментальную рассрочку. Для этого Вам необходимо иметь карту ПриватБанка. Ежемесячно с Вашего счета будет списываться фиксированная сумма.<br>
</p>
</div>
{% endblock%}

templates/returns.html
{% extends "base.html"%}
{% load static %}
{% block content%}
<div>
    <h2>
Условия и порядок возврата приобретенного бракованного товара в интернет-магазине «Bookstore» </h2>
 Данный порядок регулирует условия возврата приобретенного бракованного товара (книги, иная полиграфическая и печатная продукция и т.д.)<br>
 <br>
 1.&nbsp;Согласно Приложения №3 Постановления КМУ от 19 марта 1994 года № 172 в соответствии с положениями действующего законодательства Украины, печатная продукция надлежащего качества не подлежит возврату.<br>
 2. В случае приобретения бракованного товара, Покупатель имеет право на свой выбор бракованный товар:
<blockquote>
	<ul>
		<li>Обменять его на другой такой же, надлежащего качества; или</li>
		<li>
		Обменять его на аналогичный товар с частичной доплатой или частичным возвратом уплаченной суммы, в зависимости от стоимости аналогичного товара; или</li>
		<li>
		Получить скидку на бракованный товар, размер которой устанавливается по согласию сторон; или</li>
		<li>
		Вернуть его и получить уплаченные деньги в полном объеме.</li>
	</ul>
</blockquote>
 3. Бракованным считается товар, который имеет дефекты, полученные при транспортировке (разорванные страницы, сдавленности, потертости) или в котором допущен полиграфический брак (искажение текста, значительная потеря цвета, отсутствующие фрагменты текста, перевернутые страницы по отношению к обложке, кривой обрез, неправильная склейка и т.д.).<br>
 4.&nbsp;Согласно положениями ст. 675-676 Гражданского Кодекса Украины претензии по полиграфическому браку принимаются в течение&nbsp;6 месяцев&nbsp;с даты поставки товара Покупателю.<br>
 5. Претензии по дефектам, полученным при транспортировке, принимаются до момента передачи товара Покупателю.<br>
 6. Претензии по бракованному товару адресуются в устной форме по телефону 044-44-44-444.<br>
 7. Срок рассмотрения претензий – до 14 календарных дней с даты получения претензии.<br>
 8. В случае удовлетворения заявленной претензии:
<blockquote>
	<ul>
		<li>Если Покупатель находится в г. Киеве:</li>
	</ul>
	 К нему направляется курьер для обмена товара. Покупатель обязан передать курьеру бракованный товар и товарный чек.
	<ul>
		<li>
		Если Покупатель находится вне территории г. Киева:</li>
	</ul>
	 Покупатель самостоятельно отправляет почтой или курьерской службой бракованный товар и товарный чек на адрес магазина. Стоимость доставки бракованного товара компенсируется путем зачисления соответствующей суммы на личный счет покупателя в магазине.
</blockquote>
 9. Способ возврата денежных средств – аналогичный их получению, если иное не оговорено сторонами. <br>
 10.&nbsp;В соответствии с требованиями Налогового кодекса Украины, Покупатель для возврата денежных средств обязуется предоставить Продавцу копию паспорта и идентификационного кода Покупателя, согласно требований Закона Украины «О защите персональных данных».
<p>
</p>
<p>
</p>
 <br>
<p>
</p>
<p>
 <br>
</p>
</div>
{% endblock %}

templates/sidebar.html
{% load static %}
<div class="col-lg-3">


        <div class="list-group">
           {% for category in categories%}
          <a href={{category.get_absolute_url}} class="list-group-item">{{ category }}</a>
          {% endfor%}
        </div>
    <div class="delivery">
        <img src="{% static 'img/delivery.png' %}" alt="">
    </div>

</div>
<!-- /.col-lg-3 -->

templates/slider.html
<div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
          <ol class="carousel-indicators">
              {% for image_len in images_for_slider %}
              {% if forloop.first%}
            <li data-target="#carouselExampleIndicators" data-slide-to="{{ forloop.counter0 }}" class="active"></li>
              {% else %}
            <li data-target="#carouselExampleIndicators" data-slide-to="{{ forloop.counter0 }"></li>
               {% endif %}
              {% endfor %}
          </ol>
          <div class="carousel-inner" role="listbox">
              {% for image_item in images_for_slider %}
              {% if forloop.first%}
            <div class="carousel-item active">
                <a href="{{image_item.get_absolute_url}}" >
              <img class="d-block img-fluid" src="{{image_item.image.url}}" alt="First slide">
                </a>
            </div>
              {% else %}
            <div class="carousel-item">
              <a href="{{image_item.get_absolute_url}}" >
              <img class="d-block img-fluid" src="{{image_item.image.url}}" alt="First slide">
                </a>
            </div>
              {% endif %}
              {% endfor %}

          </div>
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
</div>