book/urls.py
from django.contrib import admin
from django.urls import include, path

from django.urls import path, re_path

from . import views


app_name ="book"


urlpatterns = [
    re_path(r'^(?P<slug>[-\w]+)/$', views.BookDetailView.as_view(), name='book-detail'),
    re_path(r'^category/(?P<category_slug>[-\w]+)/$', views.CategoryDetailView.as_view(), name='list_category'),
    re_path(r'^$', views.BookListView.as_view(), name="book_list")

]

bookstore/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from book import views


urlpatterns = [
      path('orders/', include('orders.urls')),
      path('books/', include('book.urls')),
      re_path(r'^delivery/$', TemplateView.as_view(template_name='delivery.html'), name="delivery"),
      re_path(r'^payments/$', TemplateView.as_view(template_name='payments.html'), name="payments"),
      re_path(r'^grafik-raboty/$', TemplateView.as_view(template_name='grafic.html'), name="grafik-raboty"),
      re_path(r'^returns/$', TemplateView.as_view(template_name='returns.html'), name="returns"),
      re_path(r'^about/$', TemplateView.as_view(template_name='about.html'), name="about"),
      path('admin/', admin.site.urls),
      path('', include('book.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
              # + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \

orders/urls.py
from django.contrib import admin
from django.urls import include, path

from django.urls import path, re_path

from . import views

app_name = 'orders'

urlpatterns = [
    re_path('^basket_adding/$', views.basket_adding, name='basket_adding'),
    re_path('^cart/$', views.cart, name='cart'),
    re_path('^checkout/$', views.checkout, name='checkout'),
    re_path('^remove_from_cart/$', views.remove_from_cart_view, name='remove_from_cart'),
    re_path('^count_cart/$', views.basket_count, name='basket_count'),
    re_path('^change_item_qty/$', views.change_item_qty, name='change_item_qty'),
    re_path('^order/$', views.order_create_view, name='create_order'),
    re_path('^make_order/$', views.make_order, name='make_order'),
]

orders/models.py
from django.db import models
from book.models import Book
from django.urls import reverse
from django.db.models.signals import post_save
from django.contrib.auth.models import User
# Create your models here.


class Status(models.Model):
    name = models.CharField(max_length=24, blank=True,null=True, default=None)
    is_active = models.BooleanField(default=True)
    comments = models.CharField(max_length=64,blank=True, null=True, default=None)
    updated = models.DateField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return 'Статус {}'.format(self.name)

    class Meta:
        verbose_name = 'Статус заказа'
        verbose_name_plural = 'Статутсы заказов'


class Order(models.Model):
    user = models.ForeignKey(User,blank=True, null=True, default=None, on_delete=models.CASCADE)
    total_price = models.DecimalField(max_digits=7, decimal_places=2, default=None, null=True)#total price in order
    first_name = models.CharField(max_length=64, blank=True, null=True, default=None)
    last_name = models.CharField(max_length=64, blank=True, null=True, default=None)
    phone = models.CharField(max_length=48, blank=True, null=True, default=None)
    address = models.CharField(max_length= 128, blank=True, null=True, default=None)
    buying_type = models.CharField(max_length=40,choices=(('Самовывоз','Самовывоз'),('Доставка','Доставка')),default='Самовывоз')
    status = models.ForeignKey(Status, on_delete=models.CASCADE, blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True)
    comments = models.CharField(max_length=64, blank=True, null=True, default=None)
    created = models.DateField(auto_now_add=True, auto_now=False)
    updated = models.DateField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return 'Заказ {},{}'.format(self.id, self.status)

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def save(self, *args, **kwargs):
        super(Order, self).save(*args, **kwargs)


class ProductInOrder(models.Model):
    order = models.ForeignKey(Order, blank=True,null=True, default=None,on_delete=models.CASCADE)
    book = models.ForeignKey(Book, blank=True, null=True, default=None,on_delete=models.CASCADE)
    number = models.PositiveIntegerField(default=1)
    price_per_item = models.DecimalField(max_digits=7, decimal_places=2, default=None)
    total_price = models.DecimalField(max_digits=7, decimal_places=2, default=None)#number*price
    is_active = models.BooleanField(default=True)
    created = models.DateField(auto_now_add=True, auto_now=False)
    updated = models.DateField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return '{}'.format(self.book.name)

    class Meta:
        verbose_name = 'Книга в заказе'
        verbose_name_plural = 'Книги  в заказе'

    def save(self, *args, **kwargs):
        if self.book is not None:
            price_per_item = self.book.price
            self.price_per_item = price_per_item
            self.total_price = int(self.number) * price_per_item
            super(ProductInOrder, self).save(*args, **kwargs)
        else:
            print('///none///')

def product_in_order_post_save(sender, instance, **kwargs):
    order = instance.order
    all_book_in_order = ProductInOrder.objects.filter(order=order, is_active=True)
    order_total_price = 0
    for item in all_book_in_order:
        order_total_price += item.total_price
    instance.order.total_price = order_total_price
    instance.order.save(force_update=True)


post_save.connect(product_in_order_post_save, sender=ProductInOrder)


class ProductInBasket(models.Model):
    session_key = models.CharField(max_length=128,blank=True,null=True, default=None)
    order = models.ForeignKey(Order, blank=True,null=True, default=None,on_delete=models.CASCADE)
    book = models.ForeignKey(Book, blank=True, null=True, default=None,on_delete=models.CASCADE)
    number = models.PositiveIntegerField(default=1)
    price_per_item = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    total_price = models.DecimalField(max_digits=7, decimal_places=2, default=0 )#number*price
    is_active = models.BooleanField(default=True)
    created = models.DateField(auto_now_add=True, auto_now=False)
    updated = models.DateField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return '{}'.format(self.book)


    class Meta:
        verbose_name = 'Книга в корзине'
        verbose_name_plural = 'Книги  в корзине'


    def save(self, *args, **kwargs):
        price_per_item = self.book.price
        self.price_per_item = price_per_item
        self.total_price = int(self.number) * price_per_item
        super(ProductInBasket, self).save(*args, **kwargs)

orders/forms.py
from django import forms
from django.utils import timezone
from .models import *

class OrderForm(forms.Form):
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=False)
    phone = forms.CharField()
    buying_type = forms.ChoiceField(widget=forms.Select(),choices=([("self", "самовывоз"),("delivery" ,"Доставка")]))
    address = forms.CharField(required=False)
    comments = forms.CharField(widget=forms.Textarea, required=False)


    def __init__(self,*args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].label='Имя'
        self.fields['last_name'].label = 'Фамилия'
        self.fields['phone'].label = 'Контактный телефон'
        self.fields['phone'].help_text = 'Пожалуйста, указывайте реальный номер телефона, по которому с Вами можно связатся'
        self.fields['buying_type'].label = 'Способ получения'
        self.fields['address'].label = 'Адрес доставки'
        self.fields['address'].help_text = '*Обязательно указывайте город!'
        self.fields['comments'].label = 'Комментарии к заказу'

orders/views.py
from django.shortcuts import render,reverse
from django.http import JsonResponse, HttpResponseRedirect
from . models import ProductInBasket, ProductInOrder, Order, Status
from .forms import OrderForm
from django.contrib.auth.models import User
# Create your views here.
def basket_adding(request):
    session_key = request.session.session_key
    data = request.POST
    product_id = data.get('product_id')
    nmb = data.get('nmb')
    new_product,created = ProductInBasket.objects.get_or_create(session_key=session_key,book_id=product_id,is_active=True, defaults={'number':nmb})
    if not created:
        new_product.number += int(nmb)
        new_product.save(force_update=True)
    return JsonResponse(Product_in_basket(session_key))


def Product_in_basket(session_key):
    return_dict = dict()
    products_in_basket = ProductInBasket.objects.filter(session_key=session_key, is_active=True)
    products_total_nmb = products_in_basket.count()
    return_dict['products_total_nmb'] = products_total_nmb
    return_dict['products'] = list()
    for item in products_in_basket:
        product_dict = {}
        product_dict['name'] = item.book.name
        product_dict['id'] = item.id
        product_dict['price_per_item'] = item.price_per_item
        product_dict['number'] = item.number
        return_dict['products'].append(product_dict)
    return return_dict


def basket_count(request):
    session_key = request.session.session_key
    return JsonResponse(Product_in_basket(session_key))


def remove_from_cart_view(request):
    session_key = request.session.session_key
    product_id = request.GET.get('product_id')
    ProductInBasket.objects.filter(id=product_id).update(is_active=False)
    return JsonResponse(Product_in_basket(session_key))


def make_order(request):
    session_key = request.session.session_key
    form = OrderForm(request.POST)
    if request.POST:
        if form.is_valid():
            print('yes valid')
            first_name = form.cleaned_data.get('first_name')
            last_name = form.cleaned_data.get('last_name')
            phone = form.cleaned_data.get('phone')
            buying_type = form.cleaned_data.get('buying_type')
            address = form.cleaned_data.get('address')
            comments = form.cleaned_data.get('comments')
            user, created = User.objects.get_or_create(username=phone, defaults={'first_name': first_name})
            order = Order.objects.create(user=user, first_name=first_name, phone=phone, status_id =1,
                                         last_name=last_name,buying_type=buying_type,address=address,
                                         comments=comments)
            products_in_basket = ProductInBasket.objects.filter(session_key=session_key, is_active=True)
            for product in products_in_basket:
                product_id = product.id
                value =product.number
                product_in_basket = ProductInBasket.objects.get(id=product_id)
                product_in_basket.number = value
                product_in_basket.order = order
                product_in_basket.save(force_update=True)

                ProductInOrder.objects.create(book=product_in_basket.book, number=product_in_basket.number,
                                              price_per_item=product_in_basket.price_per_item,
                                              total_price=product_in_basket.total_price,
                                              order=order)


            return render(request, 'orders/thank_you.html', locals())


def cart(request):
    session_key = request.session.session_key
    products_in_basket = ProductInBasket.objects.filter(session_key=session_key, is_active=True)
    return render(request, 'orders/cart.html', locals())

def change_item_qty(request):
    session_key = request.session.session_key
    product_basket_id=request.GET.get('product_basket_id')
    qty=request.GET.get('qty')
    product_in_basket = ProductInBasket.objects.get(id=int(product_basket_id))
    product_in_basket.number = qty
    product_in_basket.save(force_update=True)
    return JsonResponse({'ok' : 'ok'})


def checkout(request):
    session_key = request.session.session_key
    products_in_basket = ProductInBasket.objects.filter(session_key=session_key, is_active=True)
    return render(request, 'orders/checkout.html', locals())


def order_create_view(request):
    session_key = request.session.session_key
    products_in_basket = ProductInBasket.objects.filter(session_key=session_key, is_active=True)
    form = OrderForm(request.POST)
    context={
        'form':form
    }
    return render(request,'orders/order.html', context)

templates/orders/cart.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container">

        {% if products_in_basket %}
                    <div class="text-header">
            <h3 class="text-center"> Товары в корзине </h3>
        </div>


                         <table class="table">
                             <thead>
                                 <tr>
                                 <th scope="col">Название товара</th>
                                 <th scope="col">Количество</th>
                                 <th scope="col">Цена за еденицу</th>
                                 <th scope="col">Общая цена</th>
                                 <th>Действия</th>
                                 </tr>
                             </thead>
                             <tbody class="basket-count " data-products_in_basket="{{products_in_basket}}">
                             {% for product_in_basket in products_in_basket %}
                                 <tr class="cart-item-{{product_in_basket.id}} scope='row' ">
                                     <td>{{product_in_basket.book.name}}</td>

                                     <td class="product_in_basket_nmb" >
                                         <form  class="form-inline cart-qty" method="GET" action="{% url 'orders:change_item_qty'%}">
                                             <input value="{{product_in_basket.number}}" type="number" class="product-in-basket-nmb cart-item-qty"
                                                name="product_in_basket_{{product_in_basket.id}}" min="1" style="width:50px"
                                                     data-product_basket_id = '{{ product_in_basket.id }}'
                                                     >
                                         </form>
                                     </td>



                                     <td class="product-price">
                                         {{product_in_basket.price_per_item}}
                                     </td>
                                     <td><span class="total-product-in_basket-amount">{{product_in_basket.total_price}}</span>
                                     </td>
                                     <td>
                                         <a href="{% url 'orders:remove_from_cart'%}" class="delete_item"
                                            data-product_id = '{{ product_in_basket.id }}'>
                                             <button type="submit" class="btn btn-success btn-buy total_amount btn-sm ">
                                               удалить
                                             </button>
                                         </a>
                                     </td>
                                 </tr>
                             {% endfor %}
                             </tbody>
                         </table>

                        <div class="text-right">
                            <b>Сумма заказа:</b><span id="total_order_amount"></span>
                        </div>
                        <div class="text-right">
                            <a href="{% url 'orders:checkout'%}">
                                <button type="submit" class="btn btn-success btn-sm  ">Предварительный заказ</button>
                            </a>
                        </div>


        {% else %}
        <div class="basket-empty">
         <h3 class="text-center"> В Вашей корзине нет товаров </h3>
        {% endif %}
        </div>


</div>
{% endblock %}

templates/orders/checkout.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container">
        {% if products_in_basket %}
                    <h3 class="text-center"> Ваш предварительный заказ </h3>
                         <table class="table">
                             <thead>
                             <tr>
                             <th>Название товара</th>
                             <th>Количество</th>
                             <th>Общая цена</th>
                             </tr>
                             </thead>
                             <tbody class="basket-count " data-products_in_basket="{{products_in_basket}}">
                             {% for product_in_basket in products_in_basket %}
                                 <tr class="cart-item-{{product_in_basket.id}} ">
                                     <td>{{product_in_basket.book.name}}</td>
                                     <td class="product_in_basket_nmb" >
                                         <div class="text-center">
                                             {{product_in_basket.number}}
                                         </div>
                                     </td>

                                     <td><span class="total-product-in_basket-amount">
                                         {{product_in_basket.total_price}}
                                     </span>
                                     </td>
                                 </tr>
                             {% endfor %}
                             </tbody>
                             </table>
                        <div class="text-right">
                            <b>Сумма заказа:</b><span id="total_order_amount"></span>
                        </div>
                        <a href="{% url 'orders:create_order' %}" class="text-right">
                            <button type="submit" class="btn btn-success btn-sm ">
                                Оформить заказ
                            </button>
                        </a>
        {% endif %}
        </div>


</div>
{% endblock %}

templates/orders/order.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<h3 class="text-center"> Оформление заказа</h3>
<h5 class="text-left"> Информация для оплаты и доставки заказа</h5>
    <form action="{% url 'orders:make_order'%}" method="POST">{% csrf_token %}
            <div class="row">
                <div class="col-4">
                    {{form.first_name|as_crispy_field}}
                </div>
                <div class="col-4">
                    {{form.last_name|as_crispy_field}}
                </div>
                <div class="col-4">
                    {{form.phone|as_crispy_field}}
                </div>
            </div>
    {{form.buying_type|as_crispy_field}}
    {{form.address|as_crispy_field}}
    {{form.comments|as_crispy_field}}
    <input type="submit" class="btn btn-success" value="Оформить заказ">

</form>

{% endblock   %}

templates/orders/thank_you.html
{% extends "base.html" %}
{% load static %}


{% block content %}
<div class="col-sm-8 col-sm-offset-2">
    <h3 class="text-center"> Спасибо за Ваш заказ! Он принят в обработку. В ближайшее время менеджер с Вами свяжется</h3>
    <p class="text-center"><a href="/"><button class="btn btn-default">Вернуться к покупкам</button></a></p>
</div>
{% endblock %}